### ISSUE TITLE
exemplo de funcionalidade de exportação de metadados e datapackage

### ISSUE THREAD

**Issue by Andrelamor** [transparencia-mg/viz-metadados-frictionless#14]
https://canwin-datahub.ad.umanitoba.ca/data/dataset/thermosalinograph-data-2021

![image](https://user-images.githubusercontent.com/52294411/173847252-9d8b0b78-3ebc-4866-9450-dc7c12660b68.png)

**Comment by gabrielbdornas** [comment]
Referenciado no issue #26
