### ISSUE TITLE
[Uso] - História 1.1

### ISSUE THREAD

**Issue by Andrelamor** [transparencia-mg/viz-metadados-frictionless#15]
Como publicador de dados eu quero documentar o meu conjunto utilizando padrão de metadados [Frictionless Data](https://specs.frictionlessdata.io/) em formulário(s) web amigável, sendo possível incluir tanto propriedades ad-hoc quanto as preconizadas as preconizadas pelo padrão de metadados Frictionless Data e o resultado do trabalho facilmente visualizado ao longo do processo.

## Requisitos:

- [ ] Utilização de componentes já em desenvolvimento via ferramenta [Frictionless Components](https://components.frictionlessdata.io/?path=/story/components-schema--source) para geração de página web;
- [ ] Utilização de trabalho de design para elaboração de uma identidade visual atrativa, com símbolos e filtros, mas principalmente, que represente todos os metadados presentes nas especificações Frictionless;
- [ ] Página web deverá permitir o cadastro de propriedades ad-hoc;
- [ ] Página web deverá permitir o cadastro de todas as propriedades de um [Tabular Data Package](https://specs.frictionlessdata.io/tabular-data-package/);
- [ ] Página web deverá permitir o cadastro de todas as propriedades de um [Data Resource](https://specs.frictionlessdata.io/data-resource/);
- [ ] Página web deverá permitir o cadastro de todas as propriedades de um [Table Schema](https://specs.frictionlessdata.io/table-schema/), tais como enum e seus detalhes adicionais;
- [ ] Página web deverá realizar inferência dos tipos de dados de um Table Schema utilizando a ferramenta [
frictionless-py](https://github.com/frictionlessdata/frictionless-py);
- [ ] Página web deverá permitir o cadastro exemplos (sample values ou data preview) e notas de rodapé para Table Schemas; e
- [ ] Página web deverá utilizar-se de filtros e símbolos para deixar a visualização de todo datapackage mais amigáveis.

## Testes Automatizados

- [ ] Deve permitir incluir todas as propriedades preconizadas pelo padrão de metadados Frictionless Data;
- [ ] Deve permitir incluir propriedades ad-hoc; e
- [ ] Deve gerar erro caso [propriedades obrigatórias](https://transparencia-mg.github.io/manual-abertura/pages/002_metadados.html#metadados-obrigat%C3%B3rios-e-facultativos-no-portal-de-dados-abertos-de-minas-gerais) não sejam preenchidas.

## Entregável

Fork do repositório [Frictionless components](https://github.com/frictionlessdata/components) na organização [transparencia-mg](https://github.com/transparencia-mg) com o aprimoramento do componente [schema](https://components.frictionlessdata.io/?path=/story/components-schema--empty) e a criação dos components [Data Resource](https://specs.frictionlessdata.io/data-resource/) e [Tabular Data Package](https://specs.frictionlessdata.io/tabular-data-package/).

## Referências:

- [dbt docs](https://www.getdbt.com/mrr-playbook/#!/model/model.acme.customer_churn_month);
- [Exemplo de dados](https://i.imgur.com/67L88nc.png);
- [Símbolo para representação de chave primária, chave estrangeira, unique, required e enum com detalhes adicionais](https://dataedo.com/samples/html/Data_warehouse/doc/AdventureWorksDW_4/modules/Dimensions_97/module.html);
- Notas de rodapé é um [caso de uso](https://www.w3.org/annotation/wiki/Use_Cases/Annotating_CSV_Data) importante para dados tabulares, previsto em algumas gramaticas de tabelas (como no [pacote R gt](https://gt.rstudio.com/)). A propriedade [notes](https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/#table-notes) definida no âmbito da W3C pode ser reaproveitada para fins de [anotações gerais](https://www.w3.org/TR/tabular-data-primer/#cell-annotations), mas que deveriam ser tratadas de forma especial no dicionário de dados; e
- [Full-text fuzzy search no dicionário de dados](https://github.com/fjuniorr/age7-data-dictionary).

**Comment by gabrielbdornas** [comment]
@Andrelamor, revisei esta história para substituir a #21.

Como dito, acredito que temos que ter uma para geração da parte do front e outra para o back.

**Comment by gabrielbdornas** [comment]
Substituído pelo #28
