### ISSUE TITLE
Exemplificar visualizações de metadados relevantes

### ISSUE THREAD

**Issue by Andrelamor** [transparencia-mg/viz-metadados-frictionless#7]
* Contexto

Uma das seções do Termo de Referência é a _análise de viabilidade da contratação_, que deve justificar, em termos econômicos e técnicos, por que a alternativa escolhida para ser objeto de seleção de fornecedor é a mais indicada dentre um possível _pull_ de soluções tecnológicas disponíveis no mercado.

Análise similar é requerida, nos moldes da IN 1/2019 do Governo Federal, antes mesmo da elaboração do TR, no âmbito do artefato nominado como [_Estudo Técnico Preliminar_](https://github.com/dados-mg/projeto-contrato/blob/main/materiais-guias-referencia/IN-1-2019.md#2-estudo-t%C3%A9cnico-preliminar-da-contrata%C3%A7%C3%A3o-etpc), nas etapas de 'identificar soluções e realizar análise comparativa' e 'realizar análise comparativa de custos'

* Objetivo

Identificar e comparar as funcionalidades das soluções tecnológicas encontradas que permitem edição e visualização dos metadados.

Entretanto, as funcionalidades que são esperadas ainda não estão fixadas, o que será também objeto dos _pull requests_ que vierem a ser abertos a partir deste _issue_. Essa limitação, bem como parte da elaboração abaixo copiada pode ser encontrada [aqui](https://trello.com/c/mfd7neK7/808-elaborar-especifica%C3%A7%C3%A3o-para-visualiza%C3%A7%C3%A3o-de-data-packages-projeto-vale#comment-60a30a0b8162938aeb74cdcf):

> Um caminho aqui é apontar os problemas que temos com as visualizações do CKAN (incluindo o problema que elas somente estão disponíveis depois da publicação no CKAN).

> Na justificativa de negócio, precisamos deixar mais robusta a explicação para as principais decisões em relação ao nosso processo de documentação de um conjunto de dados. Acho que a linha de raciocinio é mais ou menos essa:
    º necessidade de utilização de um padrão de metadados para documentação
    º necessidade de documentação legível por máquina
    º necessidade de versionamento da documentação
    º necessidade de visualização da documentação
    º necessidade de publicação da documentação

> Para as duas primeiras podemos usar a base legal da própria LAI e a sinergia entre frictionless e CKAN. Para as três últimas, precisamos adaptar os argumentos da filosofia docs as code.

* Método

Uma das seções do [template de especificação adotado na DCTA para o Portal da Transparência](https://github.com/transparencia-mg/especificacoes-portal-transparencia/blob/5183327201e8f82447414acb4e220f62bbcefd52/template.md) é **Exemplos/Pesquisa**, que poderá ser utilizada temporariamente para se criar um mapa comparativo das funcionalidades encontradas.

Em paralelo, a seção **Motivação/Contexto da Demanda** pode discriminar melhor as limitações das atuais soluções empregadas (i.e. visualizações do CKAN, limitações na interoperabilidade do json criado, etc).

Para os envios a esse repositório, estará sendo adotado o fluxo padrão dos 2 issues que antecedem a este.

**Comment by fjuniorr** [comment]
O esboço inicial está finalizado e disponível em https://transparencia-mg.github.io/viz-metadados-frictionless/

Falta finalizar a especificação das necessidades.
